analyze:
    mode: deep
    async: false
    create-group: true
    solc: 0.6.6
    targets:
        - contracts/sol6/KyberNetwork.sol
        - contracts/sol6/KyberHintHandler.sol
        - contracts/sol6/KyberMatchingEngine.sol
        - contracts/sol6/Dao/KyberDao.sol
        - contracts/sol6/Dao/KyberStaking.sol
        - contracts/sol6/Dao/KyberFeeHandler.sol
        - contracts/sol6/KyberNetworkProxy.sol
        - contracts/sol6/KyberHistory.sol
        - contracts/sol6/KyberStorage.sol